# Generated by Django 3.2.18 on 2023-04-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('codigo_postal', models.IntegerField()),
                ('pais', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=15)),
                ('nacionalidad', models.CharField(max_length=20)),
            ],
        ),
    ]
