# Generated by Django 3.2.18 on 2023-04-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_personas'),
    ]

    operations = [
        migrations.CreateModel(
            name='sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('fono', models.IntegerField(max_length=20)),
                ('cantidad_trabajadores', models.IntegerField(max_length=255)),
                ('codigo_postal', models.IntegerField()),
                ('hora_atencion', models.TimeField()),
            ],
        ),
    ]
