# Generated by Django 3.2.18 on 2023-04-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='cantidad_trabajadores',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='fono',
            field=models.CharField(max_length=20),
        ),
    ]
